import { ASSISTANT_NAME } from "@/llm/constants";

const beginningWakeWords = [
  ASSISTANT_NAME,
  `what up ${ASSISTANT_NAME}`,
  `what's up ${ASSISTANT_NAME}`,
  `what is up ${ASSISTANT_NAME}`,
  `how's it going ${ASSISTANT_NAME}`,
  `hello ${ASSISTANT_NAME}`,
  `hey ${ASSISTANT_NAME}`,
  `hi ${ASSISTANT_NAME}`,
  `ok ${ASSISTANT_NAME}`,
  `so ${ASSISTANT_NAME}`,
  `yo ${ASSISTANT_NAME}`,
  `greetings ${ASSISTANT_NAME}`,
  `salutations ${ASSISTANT_NAME}`,
  `listen ${ASSISTANT_NAME}`,
  `hey there ${ASSISTANT_NAME}`,
  `good morning ${ASSISTANT_NAME}`,
  `good afternoon ${ASSISTANT_NAME}`,
  `good evening ${ASSISTANT_NAME}`,
  `what can you do ${ASSISTANT_NAME}`,
  `can you help me ${ASSISTANT_NAME}`,
  `assist me ${ASSISTANT_NAME}`,
  `let's talk ${ASSISTANT_NAME}`,
  `let's chat ${ASSISTANT_NAME}`,
  `wake up ${ASSISTANT_NAME}`,
  `time to wake ${ASSISTANT_NAME}`,
  `start ${ASSISTANT_NAME}`,
  `activate ${ASSISTANT_NAME}`,
  `summon ${ASSISTANT_NAME}`,
  `call ${ASSISTANT_NAME}`,
  `bring up ${ASSISTANT_NAME}`,
  `hey buddy ${ASSISTANT_NAME}`,
  `hey friend ${ASSISTANT_NAME}`,
  `hello there ${ASSISTANT_NAME}`,
  `what's cooking ${ASSISTANT_NAME}`,
  `what's new ${ASSISTANT_NAME}`,
  `let's go ${ASSISTANT_NAME}`,
  `let's get started ${ASSISTANT_NAME}`,
  `please ${ASSISTANT_NAME}`,
  `I need you ${ASSISTANT_NAME}`,
  `join me ${ASSISTANT_NAME}`,
  `come here ${ASSISTANT_NAME}`,
  `speak to me ${ASSISTANT_NAME}`,
  `talk to me ${ASSISTANT_NAME}`,
  `help me out ${ASSISTANT_NAME}`,
  `assist me now ${ASSISTANT_NAME}`,
  `get my attention ${ASSISTANT_NAME}`,
  `show me ${ASSISTANT_NAME}`,
  `let's begin ${ASSISTANT_NAME}`,
  `let's see ${ASSISTANT_NAME}`,
  `let's figure this out ${ASSISTANT_NAME}`,
  `I want to talk ${ASSISTANT_NAME}`,
  `let's have a chat ${ASSISTANT_NAME}`,
  `let's connect ${ASSISTANT_NAME}`,
  `hey ${ASSISTANT_NAME} buddy`,
  `yo ${ASSISTANT_NAME} yo`,
  `hi there ${ASSISTANT_NAME}`,
  `okie dokie ${ASSISTANT_NAME}`,
  `hey you ${ASSISTANT_NAME}`,
  `listen up ${ASSISTANT_NAME}`,
  `gimme ${ASSISTANT_NAME}`,
  `hey ${ASSISTANT_NAME} listen`,
  `yo ${ASSISTANT_NAME} what’s up`,
  `what's up ${ASSISTANT_NAME} hey`,
  `let's talk about ${ASSISTANT_NAME}`,
  `let's chat ${ASSISTANT_NAME} now`,
  `wake ${ASSISTANT_NAME} up`,
  `time wake ${ASSISTANT_NAME}`,
  `start it ${ASSISTANT_NAME}`,
  `call me ${ASSISTANT_NAME}`,
  `bring ${ASSISTANT_NAME} up`,
  `hey ${ASSISTANT_NAME} friend`,
  `assistant ${ASSISTANT_NAME}`,
  `hey ${ASSISTANT_NAME} you`,
  `what's new ${ASSISTANT_NAME} hey`,
  `let's go ${ASSISTANT_NAME} now`,
  `let's get started ${ASSISTANT_NAME} please`,
  `yes ${ASSISTANT_NAME}`,
  `ye ${ASSISTANT_NAME}`,
  `yeah ${ASSISTANT_NAME}`,
  `yeh ${ASSISTANT_NAME}`,
  `yay ${ASSISTANT_NAME}`,
  `no ${ASSISTANT_NAME}`,
  `na ${ASSISTANT_NAME}`,
  `nah ${ASSISTANT_NAME}`,
  `nope ${ASSISTANT_NAME}`,
  `cheers ${ASSISTANT_NAME}`,
  `much appreciated ${ASSISTANT_NAME}`,
  `i appreciate it ${ASSISTANT_NAME}`,
  `thank ${ASSISTANT_NAME}`,
  `thank you ${ASSISTANT_NAME}`,
  `thanks ${ASSISTANT_NAME}`,
];

const endingWakeWords = [
  `${ASSISTANT_NAME}`,
  `thank you ${ASSISTANT_NAME}`,
  `thanks ${ASSISTANT_NAME}`,
  `that's all ${ASSISTANT_NAME}`,
  `stop ${ASSISTANT_NAME}`,
  `thanks ${ASSISTANT_NAME}`,
  `goodbye ${ASSISTANT_NAME}`,
  `see you ${ASSISTANT_NAME}`,
  `catch you later ${ASSISTANT_NAME}`,
  `talk to you later ${ASSISTANT_NAME}`,
  `bye ${ASSISTANT_NAME}`,
  `end ${ASSISTANT_NAME}`,
  `dismiss ${ASSISTANT_NAME}`,
  `close ${ASSISTANT_NAME}`,
  `exit ${ASSISTANT_NAME}`,
  `that's it ${ASSISTANT_NAME}`,
  `no more ${ASSISTANT_NAME}`,
  `stop listening ${ASSISTANT_NAME}`,
  `take a break ${ASSISTANT_NAME}`,
  `pause ${ASSISTANT_NAME}`,
  `hold on ${ASSISTANT_NAME}`,
  `let's wrap it up ${ASSISTANT_NAME}`,
  `finish up ${ASSISTANT_NAME}`,
  `that's enough ${ASSISTANT_NAME}`,
  `shut down ${ASSISTANT_NAME}`,
  `power down ${ASSISTANT_NAME}`,
  `sign off ${ASSISTANT_NAME}`,
  `let's end this ${ASSISTANT_NAME}`,
  `stop for now ${ASSISTANT_NAME}`,
  `let's take a break ${ASSISTANT_NAME}`,
  `thank ${ASSISTANT_NAME}`,
  `thanks a lot ${ASSISTANT_NAME}`,
  `goodbye for now ${ASSISTANT_NAME}`,
  `see ya ${ASSISTANT_NAME}`,
  `catch ya later ${ASSISTANT_NAME}`,
  `talk later ${ASSISTANT_NAME}`,
  `bye bye ${ASSISTANT_NAME}`,
  `end it ${ASSISTANT_NAME}`,
  `dismiss it ${ASSISTANT_NAME}`,
  `close it ${ASSISTANT_NAME}`,
  `that's all for now ${ASSISTANT_NAME}`,
  `no more talking ${ASSISTANT_NAME}`,
  `stop it ${ASSISTANT_NAME}`,
  `take a break now ${ASSISTANT_NAME}`,
  `pause it ${ASSISTANT_NAME}`,
  `hold it ${ASSISTANT_NAME}`,
  `let's wrap this up ${ASSISTANT_NAME}`,
  `finish it ${ASSISTANT_NAME}`,
  `that's enough for now ${ASSISTANT_NAME}`,
  `shut it down ${ASSISTANT_NAME}`,
  `power it down ${ASSISTANT_NAME}`,
  `sign off now ${ASSISTANT_NAME}`,
  `let's end this now ${ASSISTANT_NAME}`,
  `stop for the moment ${ASSISTANT_NAME}`,
  `let's take a break now ${ASSISTANT_NAME}`,
];

export const hasWakeWord = (prompt: string): boolean => {
  const cleanPrompt = prompt.trim().toLowerCase().replace(/,/gi, "");
  return (
    beginningWakeWords.some(word => cleanPrompt.startsWith(word.toLowerCase())) ||
    endingWakeWords.some(word => cleanPrompt.endsWith(word.toLowerCase()))
  );
};
